id: ADA553893
base_file: f4656.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:00:42.019348
  last_modified_at: 2022-06-17 13:00:42.019371
